apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploysnr
  labels:
    app: autodeploysnr
  namespace: namespace-workflow-1708350451107
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploysnr
  template:
    metadata:
      labels:
        app: autodeploysnr
    spec:
      containers:
        - name: autodeploysnr
          image: acrworkflow1708350451107.azurecr.io/image-workflow-1708350451107:latest
          ports:
            - containerPort: 5000