apiVersion: v1
kind: Service
metadata:
  name: autodeploysnr
  namespace: namespace-workflow-1708350451107
spec:
  type: LoadBalancer
  selector:
    app: autodeploysnr
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000